# Generated by Django 3.2.13 on 2022-05-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
