# Generated by Django 3.2.13 on 2022-05-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_itemmodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ('id',)},
        ),
    ]
